### PR TITLE
XDR-78: fix to upload files with cyrillic sympols in filename (on win…

### LINKED ISSUE #18: Could't upload file with the Cyrillic name
**Step to reproduce**:
- send a Cyrillic file in the path or name via http

**Environment**:
On Windows

**Actual result**:
Error when submitting and via vxapi and when triggering an event with a dispatch action assigned

file_uploader_cyrrilic

**Expected result**:
File sended

### PR DESCRIPTION
**Pull request by BurovAV**
require "fs" for fix to upload files with cyrillic symbols in filename.
Closed #18

### CODE REVIEW

**Comment by Arkweid** [comment]
Looks like `local lfs = require("lfs")` doesn't need any more.
So what the difference between `lfs` and `fs`?

**Comment by asdek** [comment]
@BurovAV @Arkweid sorry guys, `lfs` perfectly work with utf-8 strings, could you give a proof about the issue?

**Comment by BurovAV** [comment]
@asdek The Windows agent does not work with files that have Cyrillic characters in their names.

**Review by asdek — APPROVED** [review]

**Comment by asdek** [comment]
@BurovAV could you squash your commits and resign its or sign your first commit?

**Comment by BurovAV** [comment]
I create new PR - https://github.com/vxcontrol/soldr-modules/pull/34

**Pull request closed without merging**
